spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stock_plat
    password: 123456
    url: jdbc:mysql://192.168.6.123:3306/stock_plat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    cluster:
      nodes: 192.168.0.111:6379,192.168.0.112:6379,192.168.0.113:6379,192.168.0.114:6379,192.168.0.115:6379,192.168.0.116:6379
    #    host: 192.168.31.50
#    pool: 6379
    timeout: 5000
    database: 0

# swagger开关
swagger:
  enable: true

# mybatis_plus sql打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 签名密钥
secret: 123456789
